-- =============================================================================
-- DermaAI Supabase Database Schema & Row Level Security (RLS)
-- Execute this SQL script in your Supabase SQL Editor
-- =============================================================================

-- 1. USERS PROFILES TABLE
-- Stores user skin characteristics, sensitivities, and allergies collected during the Wizard
CREATE TABLE IF NOT EXISTS public.users_profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  name TEXT,
  skin_type TEXT CHECK (skin_type IN ('Oily', 'Dry', 'Combo', 'Normal', 'Sensitive')),
  skin_shade TEXT,
  allergies TEXT[] DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. SCANS TABLE
-- Stores dermatological product analysis results generated by Gemini AI engine
CREATE TABLE IF NOT EXISTS public.scans (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  product_name TEXT NOT NULL,
  compatibility_status TEXT NOT NULL CHECK (compatibility_status IN ('Compatible', 'Not Compatible')),
  reasoning TEXT NOT NULL,
  scanned_at TIMESTAMPTZ DEFAULT NOW()
);

-- Index for performance when querying user scan history
CREATE INDEX IF NOT EXISTS idx_scans_user_id_scanned_at ON public.scans(user_id, scanned_at DESC);

-- =============================================================================
-- ROW LEVEL SECURITY (RLS) POLICIES
-- Security First: Ensure users can strictly access only their own data
-- =============================================================================

-- Enable RLS on users_profiles
ALTER TABLE public.users_profiles ENABLE ROW LEVEL SECURITY;

-- users_profiles policies
CREATE POLICY "Users can read own profile"
  ON public.users_profiles
  FOR SELECT
  USING (auth.uid() = id);

CREATE POLICY "Users can insert own profile"
  ON public.users_profiles
  FOR INSERT
  WITH CHECK (auth.uid() = id);

CREATE POLICY "Users can update own profile"
  ON public.users_profiles
  FOR UPDATE
  USING (auth.uid() = id)
  WITH CHECK (auth.uid() = id);

-- Enable RLS on scans
ALTER TABLE public.scans ENABLE ROW LEVEL SECURITY;

-- scans policies
CREATE POLICY "Users can read own scans"
  ON public.scans
  FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own scans"
  ON public.scans
  FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete own scans"
  ON public.scans
  FOR DELETE
  USING (auth.uid() = user_id);
